package me.songha.simple.member.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;

import java.time.ZonedDateTime;

@NoArgsConstructor(access = AccessLevel.PROTECTED)
@ToString
//@EqualsAndHashCode
@Getter
@Table(name = "MEMBER")
@Entity
public class Member {

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    private Long id;

    @NotNull
    @Embedded
    private Email email;

    @Size(min = 2, max = 16) // 2~16 사이의 문자열 갯수가 아니면 exception
    @Column(length = 32) // varchar(32)
    private String nickname;

    @CreatedDate
    private ZonedDateTime createAt;

    @LastModifiedDate
    private ZonedDateTime updateAt;

    @Builder
    public Member(Email email, String nickname, ZonedDateTime createAt, ZonedDateTime updateAt) {
        this.email = email;
        this.nickname = nickname;
        this.createAt = createAt;
        this.updateAt = updateAt;
    }
}

/**
 * Hibernate:
 * create table member (
 * create_at timestamp(6) with time zone,
 * id bigint generated by default as identity,
 * update_at timestamp(6) with time zone,
 * nickname varchar(16),
 * email varchar(128) not null unique,
 * primary key (id)
 * )
 */